notifications:
  email: false

jobs:
  include:
    - stage: test
      name: All Tests
      language: php
      php: "8.0"
      services:
        - docker
      before_install:
        - docker-compose up -d
      install:
        - composer install
      script:
        - ./vendor/bin/phpunit
