services:
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_SERVICES=cloudwatch
    volumes:
      - ./var/localstack:/var/lib/localstack
      - ./docker/localstack/ready.d:/etc/localstack/init/ready.d
