services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    volumes:
      - ./var/localstack:/var/lib/localstack
      - ./docker/localstack/ready.d:/etc/localstack/init/ready.d
