name: ci

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: test
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
        composer-command:
          - composer install
          - composer update --prefer-lowest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: start localstack
        run: ./bin/dev/up
      - name: PHP
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ matrix.php-version }}
          composer-command: ${{ matrix.composer-command }}
      - name: tests
        run: ./bin/dev/unittest
